apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  #namespace: dev-service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ironjin92/my-app:v1
        ports:
        - containerPort: 8000
      # imagePullSecrets:
      # - name: argo-docker-registry